sql.table1.select.all= SELECT \
  COD_EMPRESA, \
  COD_ATENCION, \
  FEC_CREACION, \
  COD_CANAL, \
  COD_TIP_DOCUMENTO, \
  NRO_DOCTO_IDENT, \
  NOMBRE_RAZON_SOCIAL, \
  APELLIDO_SOLICITANTE, \
  NUM_SUMINISTRO, \
  EMAIL_SOLICITANTE, \
  TELEF_SOLICITANTE, \
  DIRECCION, \
  UBIGEO, \
  COD_ASUNTO, \
  FEC_SOLUCION, \
  DESCRIPCION_RECLAMO, \
  COD_ESTADO, \
  TIP_ATENCION, \
  COD_DISTRITO \
FROM WCLIENTE.OSI_TABLA1 \
WHERE \
  (OSI_ESTADO IN ('PENDIENTE', 'ERROR') OR OSI_ESTADO IS NULL) \
  AND OSI_NUM_REINTENTO < 3 \
  AND FEC_CREACION >=  TO_DATE(?, 'YYYY-MM-DD') \
  AND FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') + 1 \
  OFFSET ? ROWS FETCH NEXT ? ROWS ONLY


sql.table1.select.count.all=SELECT \
  COUNT(*) AS TOTAL \
FROM WCLIENTE.OSI_TABLA1 \
WHERE \
  (OSI_ESTADO IN ('PENDIENTE', 'ERROR') OR OSI_ESTADO IS NULL) \
  AND OSI_NUM_REINTENTO < 3 \
  AND FEC_CREACION >=  TO_DATE(?, 'YYYY-MM-DD') \
  AND FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') + 1

sql.table1.update= UPDATE WCLIENTE.OSI_TABLA1 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?  WHERE  COD_EMPRESA = ? AND COD_ATENCION = ?

sql.table2.select.all= SELECT \
  t2.COD_ATENCION, \
  t2.COD_ACCION, \
  t2.FEC_CREACION, \
  t2.DESC_ACCION, \
  t2.COD_ESTADO_ATENCION, \
  t2.FEC_RESPUESTA \
FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA2 t2  \
  ON t1.COD_ATENCION = t2.COD_ATENCION \
  AND t1.OSI_ESTADO = 'CONFIRMADO' \
WHERE (t2.OSI_ESTADO IS NULL OR t2.OSI_ESTADO = 'PENDIENTE' OR t2.OSI_ESTADO = 'ERROR') \
  AND t2.FEC_CREACION >=  TO_DATE('2025-10-01', 'YYYY-MM-DD') \
  AND t2.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') \
  AND t2.OSI_NUM_REINTENTO < 3 OFFSET ? ROWS FETCH NEXT ? ROWS ONLY


sql.table2.select.count.all=SELECT COUNT(*) AS TOTAL \
  FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA2 t2  \
    ON t1.COD_ATENCION = t2.COD_ATENCION \
    AND t1.OSI_ESTADO = 'CONFIRMADO' \
  WHERE (t2.OSI_ESTADO IS NULL OR t2.OSI_ESTADO = 'PENDIENTE' OR t2.OSI_ESTADO = 'ERROR') \
    AND t2.FEC_CREACION >=  TO_DATE('2025-10-01', 'YYYY-MM-DD') \
    AND t2.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD')

sql.table2.update= UPDATE WCLIENTE.OSI_TABLA2 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?  WHERE  COD_ATENCION = ? AND COD_ACCION = ?


sql.table3.select.all= SELECT \
  COD_ATENCION, \
  COD_ACCION, \
  COD_INTERRUPCION, \
  FEC_INI_INTERRUPCION, \
  FEC_FIN_INTERRUPCION, \
  CANT_SUM_AFECTADOS, \
  FASE_INTERRUMPIDA, \
  POTENCIA_INTERRUMPIDA, \
  ENERGIA_NO_SUMINISTRADA, \
  COD_MOTIVO_FALLA, \
  DESCRIPCION_MOTIVO, \
  LOCALIZACION_FALLA, \
  SUST_TEC_A_INTERR_4_12, \
  SUST_TEC_A_INTERR_MAS_12, \
  SUST_TEC_C, \
  DESCR_ACC_REALIZADAS, \
  CARACT_TEC_PUESTA_OPER, \
  ACTA_INSPECCION, \
  CANT_ATENCIONES \
FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA3 t3  \
  ON t1.COD_ATENCION = t3.COD_ATENCION \
  AND t1.OSI_ESTADO = 'CONFIRMADO' \
WHERE (t3.OSI_ESTADO IS NULL OR t3.OSI_ESTADO = 'PENDIENTE' OR t3.OSI_ESTADO = 'ERROR') \
  AND t3.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') \
  AND t3.OSI_NUM_REINTENTO < 3 \
  OFFSET ? ROWS FETCH NEXT ? ROWS ONLY


sql.table3.select.count.all=SELECT COUNT(*) AS TOTAL \
  FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA3 t3  \
    ON t1.COD_ATENCION = t3.COD_ATENCION \
    AND t1.OSI_ESTADO = 'CONFIRMADO' \
    WHERE (t3.OSI_ESTADO IS NULL OR t3.OSI_ESTADO = 'PENDIENTE' OR t3.OSI_ESTADO = 'ERROR') AND t3.OSI_NUM_REINTENTO < 3 AND t3.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD')

sql.table3.update= UPDATE WCLIENTE.OSI_TABLA3 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?  WHERE  COD_ATENCION = ? AND COD_ACCION = ?


sql.table4.select.all= SELECT \
  COD_ATENCION, \
  COD_ACCION, \
  COD_ALIMENTADOR, \
  COD_SED, \
  COD_TIP_CONEX, \
  CANT_USU_AFECTADOS, \
  SUM_AFECTADOS, \
  COD_CAUSA_VAR_TENSION, \
  SUST_TEC_ORIGEN, \
  COD_MED_ATENCION, \
  FEC_ULT_APLICACION, \
  SUST_TEC_CONCLUYE, \
  COORD_UTM_X, \
  COORD_UTM_Y, \
  CANT_ATENCIONES \
FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA4 t4  \
  ON t1.COD_ATENCION = t4.COD_ATENCION \
  AND t1.OSI_ESTADO = 'CONFIRMADO' \
WHERE (t4.OSI_ESTADO IS NULL OR t4.OSI_ESTADO = 'PENDIENTE' OR t4.OSI_ESTADO = 'ERROR') \
  AND t4.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') \
  AND t4.OSI_NUM_REINTENTO < 3 \
  OFFSET ? ROWS FETCH NEXT ? ROWS ONLY


sql.table4.select.count.all=SELECT COUNT(*) AS TOTAL \
  FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA4 t4  \
    ON t1.COD_ATENCION = t4.COD_ATENCION \
    AND t1.OSI_ESTADO = 'CONFIRMADO' \
    WHERE (t4.OSI_ESTADO IS NULL OR t4.OSI_ESTADO = 'PENDIENTE' OR t4.OSI_ESTADO = 'ERROR') AND t4.OSI_NUM_REINTENTO < 3 AND t4.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD')

sql.table4.update= UPDATE WCLIENTE.OSI_TABLA4 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?   WHERE  COD_ATENCION = ? AND COD_ACCION = ?

sql.table5.select.all= SELECT \
  COD_ATENCION, \
  COD_ACCION, \
  COD_SED, \
  COD_IRREGULARIDAD, \
  ZON_GEOGRAFICA, \
  CANT_SUM_AFECTADOS, \
  MES_FAC_IRREGULARIDAD, \
  MED_CORRECTIVA, \
  SUST_TECNICO, \
  CANT_ATENCIONES \
FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA5 t5  \
  ON t1.COD_ATENCION = t5.COD_ATENCION \
  AND t1.OSI_ESTADO = 'CONFIRMADO' \
WHERE (t5.OSI_ESTADO IS NULL OR t5.OSI_ESTADO = 'PENDIENTE' OR t5.OSI_ESTADO = 'ERROR') \
  AND t5.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') \
  AND t5.OSI_NUM_REINTENTO < 3 \
  OFFSET ? ROWS FETCH NEXT ? ROWS ONLY

sql.table5.select.count.all=SELECT COUNT(*) AS TOTAL \
  FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA5 t5  \
    ON t1.COD_ATENCION = t5.COD_ATENCION \
    AND t1.OSI_ESTADO = 'CONFIRMADO' \
    WHERE (t5.OSI_ESTADO IS NULL OR t5.OSI_ESTADO = 'PENDIENTE' OR t5.OSI_ESTADO = 'ERROR') AND t5.OSI_NUM_REINTENTO < 3 AND t5.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD')

sql.table5.update= UPDATE WCLIENTE.OSI_TABLA5 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?   WHERE  COD_ATENCION = ? AND COD_ACCION = ?

sql.table6.select.all= SELECT \
  COD_ATENCION, \
  COD_ACCION, \
  COD_SIST_ELECTRICO, \
  COD_SED, \
  COD_SECTOR_TIPICO, \
  FEC_VER_CAMPO, \
  COD_DEF_TIPICA, \
  COD_UAP, \
  FEC_SUB_DEFICIENCIA, \
  NUM_ORD_TRABAJO, \
  FEC_APLIACION, \
  CANT_ATENCIONES \
FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA6 t6  \
  ON t1.COD_ATENCION = t6.COD_ATENCION \
  AND t1.OSI_ESTADO = 'CONFIRMADO' \
WHERE (t6.OSI_ESTADO IS NULL OR t6.OSI_ESTADO = 'PENDIENTE' OR t6.OSI_ESTADO = 'ERROR') \
  AND t6.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') \
  AND t6.OSI_NUM_REINTENTO < 3 \
  OFFSET ? ROWS FETCH NEXT ? ROWS ONLY

sql.table6.select.count.all=SELECT COUNT(*) AS TOTAL \
  FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA6 t6  \
    ON t1.COD_ATENCION = t6.COD_ATENCION \
    AND t1.OSI_ESTADO = 'CONFIRMADO' \
    WHERE (t6.OSI_ESTADO IS NULL OR t6.OSI_ESTADO = 'PENDIENTE' OR t6.OSI_ESTADO = 'ERROR') AND t6.OSI_NUM_REINTENTO < 3 AND t6.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD')

sql.table6.update= UPDATE WCLIENTE.OSI_TABLA6 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?  WHERE  COD_ATENCION = ? AND COD_ACCION = ?

sql.table7.select.all= SELECT \
  COD_ATENCION, \
  COD_ACCION, \
  COD_SIST_ELECTRICO, \
  COD_ALIMENTADOR, \
  COD_SED, \
  TIP_ELE_RIESGOELEC, \
  COD_ELE_RIESGOELEC, \
  EVA_CAMPO, \
  CAUSA_RIESGO, \
  DESC_MED_PREVENTIVAS, \
  SUBS_RIESGO_ELECTRICO, \
  CAUSA_NO_CUMPLIMIENTO, \
  COORD_UTM_X, \
  COORD_UTM_Y, \
  CANT_ATENCIONES \
FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA7 t7  \
  ON t1.COD_ATENCION = t7.COD_ATENCION \
  AND t1.OSI_ESTADO = 'CONFIRMADO' \
WHERE (t7.OSI_ESTADO IS NULL OR t7.OSI_ESTADO = 'PENDIENTE' OR t7.OSI_ESTADO = 'ERROR') \
  AND t7.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') \
  AND t7.OSI_NUM_REINTENTO < 3 \
  OFFSET ? ROWS FETCH NEXT ? ROWS ONLY


sql.table7.select.count.all=SELECT COUNT(*) AS TOTAL \
  FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA7 t7  \
    ON t1.COD_ATENCION = t7.COD_ATENCION \
    AND t1.OSI_ESTADO = 'CONFIRMADO' \
    WHERE (t7.OSI_ESTADO IS NULL OR t7.OSI_ESTADO = 'PENDIENTE' OR t7.OSI_ESTADO = 'ERROR') AND t7.OSI_NUM_REINTENTO < 3 AND t7.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD')

sql.table7.update= UPDATE WCLIENTE.OSI_TABLA7 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?   WHERE  COD_ATENCION = ? AND COD_ACCION = ?

sql.table8.select.all= SELECT \
  COD_ATENCION, \
  COD_ACCION, \
  COD_CENTRO_ATENCION, \
  COD_PRESUPUESTO, \
  TIP_CONEXION, \
  TIP_ACOMETIDA, \
  COD_TARIF_INI, \
  COD_TARIF_FIN, \
  POTENCIA \
FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA8 t8  \
  ON t1.COD_ATENCION = t8.COD_ATENCION \
  AND t1.OSI_ESTADO = 'CONFIRMADO' \
WHERE (t8.OSI_ESTADO IS NULL OR t8.OSI_ESTADO = 'PENDIENTE' OR t8.OSI_ESTADO = 'ERROR') \
  AND t8.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD') \
  AND t8.OSI_NUM_REINTENTO < 3 \
  OFFSET ? ROWS FETCH NEXT ? ROWS ONLY

sql.table8.select.count.all=SELECT COUNT(*) AS TOTAL \
  FROM WCLIENTE.OSI_TABLA1 t1 JOIN WCLIENTE.OSI_TABLA8 t8  \
    ON t1.COD_ATENCION = t8.COD_ATENCION \
    AND t1.OSI_ESTADO = 'CONFIRMADO' \
    WHERE (t8.OSI_ESTADO IS NULL OR t8.OSI_ESTADO = 'PENDIENTE' OR t8.OSI_ESTADO = 'ERROR') AND t8.OSI_NUM_REINTENTO < 3 AND t8.FEC_CREACION <  TO_DATE(?, 'YYYY-MM-DD')

sql.table8.update= UPDATE WCLIENTE.OSI_TABLA8 SET OSI_ESTADO = ?, OSI_NUM_REINTENTO = OSI_NUM_REINTENTO + 1, OSI_FEC_ENVIO = ?   WHERE  COD_ATENCION = ? AND COD_ACCION = ?

sql.parameters.select.all= SELECT \
  CODIGO, \
  DESCRIPCION, \
  VALOR_NUM, \
  VALOR_ALF, \
  ACTIVO \
FROM WCLIENTE.OSI_COM_PARAMETROS \
WHERE ACTIVO = 'S' AND SISTEMA = ? AND ENTIDAD = ?


sql.errorOsi.insert= INSERT INTO WCLIENTE.OSI_ERRORES_REMISION (\
  UUID_ERROR, \
  NOMBRE_TABLA, \
  COD_ATENCION, \
  COD_ACCION, \
  MENSAJE_ERROR, \
  TIPO_ERROR, \
  CAMPO_ERRONEO, \
  CODIGO_ERROR_EXTERNO, \
  FECHA_ERROR, \
  ESTADO_ERROR, \
  COMENTARIOS_ADICIONALES, \
  USUARIO) \
  VALUES(?, ?,  ?,  ?,  ?,  ?,  ?,  ?,  ?,  ?,  ?,  ?)


sql.package.pqcorreo= {call WCLIENTE.PQCORREO.EnviarMailAttach(?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)}