#LOCAL
#db.url=jdbc:oracle:thin:@localhost:1521/JOBOSI
#db.username=WCLIENTE
#db.password=rover


#DESARROLLO
#db.url=jdbc:oracle:thin:@slaapmweod00:1521/Oweoas
#db.username=WCLIENTE
#db.password=transdes

#DESARROLLO OSY
db.url=jdbc:oracle:thin:@10.164.146.119:1521/OSYDES.comdesabdsub.comdesavnt.oraclevcn.com
db.username=synergia
db.password=Migrades00:0

#PROD
#db.url=jdbc:oracle:thin:@elaapmweod00:1521/OWEOAE
#db.username=SWFM_AYE_46678997
#db.password=TitoSalinas2025$