#LOCAL
#db.url=jdbc:oracle:thin:@localhost:1521/JOBOSI
#db.username=WCLIENTE
#db.password=rover


#DESARROLLO
db.url=jdbc:oracle:thin:@slaapmweod00:1521/Oweoas
db.username=WCLIENTE
db.password=transdes