package com.ayesa.batch.mappers.fields;

public enum Table3FieldEnum {

    COD_INTERRUPCION,
    FEC_INI_INTERRUPCION,
    FEC_FIN_INTERRUPCION,
    CANT_SUM_AFECTADOS,
    FASE_INTERRUMPIDA,
    POTENCIA_INTERRUMPIDA,
    ENERGIA_NO_SUMINISTRADA,
    COD_MOTIVO_FALLA,
    DESCRIPCION_MOTIVO,
    LOCALIZACION_FALLA,
    SUST_TEC_A_INTERR_4_12,
    SUST_TEC_A_INTERR_MAS_12,
    SUST_TEC_C,
    DESCR_ACC_REALIZADAS,
    CARACT_TEC_PUESTA_OPER,
    ACTA_INSPECCION
}
